package com.mycompany.ist412_group5.view;


import com.mycompany.ist412_group5.controller.TicketController;


import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jed Elijah Galvo
 */
public class TicketView<object> extends JPanel {
    private TicketController ticketController;
    private HomeView homeView;
    ArrayList<Integer> tempTicket = new ArrayList<>();
    int ticketPurchase = 0;
    int ticketTotal = 0;
    int ticketRemaining = 1000;
    JButton OKButton = new JButton("OK");
    Scanner Scanner = new Scanner(System.in);
    String userID;
    JTextField textField2 = new JTextField();
    JComboBox jComboBox1 = new JComboBox();
    JTextField textField3 = new JTextField();
    JPanel jPanel1Purchase = new JPanel();

    /**
     * Creates new form Cart
     */
    public TicketView(HomeView homeView, TicketController ticketController) {
        this.homeView = homeView;
        this.ticketController = ticketController;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {


        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();


        jPanel1 = new javax.swing.JPanel(new BorderLayout());
        jPanel2 = new javax.swing.JPanel();
        //jFrame1 = (JFrame) SwingUtilities.getWindowAncestor(jPanel2);
        jLabel2.setVisible(true);
        jLabel1.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);

        jLabel2.setText("Buy Ticket");
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });


        jLabel5.setText("View Ticket");
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });


        jLabel1.setText("Cancel Tickets");
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)
                                                .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1)))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jButton3))
                                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton3)
                                        .addComponent(jButton2))
                                .addContainerGap(97, Short.MAX_VALUE))
        );


        jPanel1.add(jPanel2);
        homeView.updateMainContentPanel(jPanel1);

    }// </editor-fold>//GEN-END:initComponents

    /*
     With this button click; It would go straight into  the checkout Class.

     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CheckOut CO = new CheckOut();
        CO.viewingTickets();


    }//GEN-LAST:event_jButton3ActionPerformed

    /*
    Clicking onto the Buy button would allow the user to purchase tickets; Up to eight tickets!
    Clicking onto this button when Total Tickets reaches 0 will give a message to the user "We do not have anymore"
    Clicking onto this button more than eight times will yield another message to the user "That is too many tickets!"
    */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int key = 0;
        ticketTotal = 0;
        jLabel2.setVisible(false);
        jLabel1.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        OKButton.setVisible(true);


        JPanel panel = new JPanel(new BorderLayout());
        JLabel jLabel1 = new JLabel("Quantity Tickets: ");
        JLabel jLabel2 = new JLabel("Payment Method: ");
        JLabel jLabel3 = new JLabel("Price: ");
        textField3.setEditable(false);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"VISA", "MasterCard", "Amex", "Chase", "CapitalOne"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(panel);
        panel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(130, 130, 130)
                                                .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(129, 129, 129)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(80, 80, 80)
                                                        .addComponent(jLabel1)
                                                        .addGap(26, 26, 26)
                                                        .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(66, 66, 66)
                                                        .addComponent(OKButton)
                                                        .addGap(23, 23, 23))))
                                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(39, 39, 39)
                                .addComponent(OKButton)
                                .addContainerGap(52, Short.MAX_VALUE))
        );


        panel.add(jPanel1Purchase);
        homeView.updateMainContentPanel(panel);

        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });



/*
            if(temp == 0){JOptionPane.showMessageDialog(null, "The amount of ticket purchase needs to be higher than 0.");}
            else{
                var decision =JOptionPane.showInputDialog(null, "are you ready to purchase? Type in Yes or No.");
                if("Yes".equals(decision) || "yes".equals(decision)){key = 1; break;}
            }
            */


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {


        String  MethodPayment = String.valueOf(jComboBox1.getSelectedItem());
        int AmountTickets = Integer.parseInt(textField2.getText());
        System.out.println(AmountTickets);
        MethodPayment = textField2.getText();
        tempTicket.add(AmountTickets);

        if (AmountTickets == 0) {
            JOptionPane.showMessageDialog(null, "The tickets purchase needs to be higher than 0");
        } else {
            for (int i = 0; i <= tempTicket.size() - 1; i++) {
                ticketTotal = ticketTotal + tempTicket.get(i);
                ticketRemaining = ticketRemaining - tempTicket.get(i);
            }
        }
        com.mycompany.ist412_group5.model.ticketing.Price p = new com.mycompany.ist412_group5.model.ticketing.Price();
        float ticketPrice = p.getPrice();
        double total = Math.round((ticketPrice * ticketTotal) * 100.00) / 100.00;
        System.out.println(total);
        textField3.setText(String.valueOf("$" + total));


        switch(MethodPayment) {

            case "VISA":
                confirmPurchase();
                break;
            case "MasterCard":
                confirmPurchase();
                break;
            case "Amex":
                confirmPurchase();
                break;
            case "Chase":
                confirmPurchase();
                break;
            case "CapitalOne":
                confirmPurchase();
                break;


            default:
                JOptionPane.showMessageDialog(null, "Invalid Method Card Payment: Try again with another card.");
        }


        System.out.println(ticketTotal + " " + ticketRemaining);
        tempTicket.clear();
    }

    private void confirmPurchase() {
        JOptionPane.showMessageDialog(null, "HEY!");
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CheckOut CO = new CheckOut();
        CO.viewingTicketsCancel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed


    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables


}

